print u"    \U0001F407                         \U0001F407"
print u"   \U0001F484\U0001F484\U0001F484                       \U0001F484\U0001F484\U0001F484"
print "   RRRRR                    RRRRR"
print "   RRRRR                    RRRRR"
print "   RRRRR                    RRRRR"
print "   RRRRR                    RRRRR"
print "   RRRR      RRRRRRRRRR      RRRR"
print "    RRR RRRRRRRRRRRRRRRRRRRR RRR"
print "    RRRRRRRRRRRRRRRRRRRRRRRRRRRR "
print "   RRRRRRRRRRRRRRRRRRRRRRRRRRRRRR"
print "  RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR"
print "  RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR"
print "  RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR"
print "  RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR"
print "   RRRRRRRRRRRRRRRRRRRRRRRRRRRRRR"
print "    RRRRRRRRRRRRRRRRRRRRRRRRRRRR"
print "     RRRRRRRRRRRRRRRRRRRRRRRRRR"
print "      RRRRRRRRRRRRRRRRRRRRRRRR"
print "       RRRRRRRRRRRRRRRRRRRRRR"
print "        RRRRRRRRRRRRRRRRRRRR"
print "            RRRRRRRRRRRR"
#need it to print the information
#the unicodes make up the ears
#Need to use randomizer to get the information to randomize
